const UDEMY_LOAD_COURSES_SUCCESS = "UDEMY_LOAD_COURSES_SUCCESS";
const UDEMY_LOAD_COURSES_FAIL = "UDEMY_LOAD_COURSES_FAIL";
const UDEMY_LOAD_COURSES_INIT = "UDEMY_LOAD_COURSES_INIT";

const COURSES_LOAD_INIT = "COURSES_LOAD_INIT";
const COURSES_LOAD_FAILT = "COURSES_LOAD_FAILT";
const COURSES_LOAD_SUCCESS = "COURSES_LOAD_SUCCESS";
export {
    UDEMY_LOAD_COURSES_SUCCESS,
    UDEMY_LOAD_COURSES_FAIL,
    UDEMY_LOAD_COURSES_INIT,
    COURSES_LOAD_INIT,
    COURSES_LOAD_FAILT,
    COURSES_LOAD_SUCCESS
}