const UDEMY_LOAD_COURSES_SUCCESS ="UDEMY_LOAD_COURSES_SUCCESS";
const UDEMY_LOAD_COURSES_FAIL ="UDEMY_LOAD_COURSES_FAIL";
const UDEMY_LOAD_COURSES_INIT ="UDEMY_LOAD_COURSES_INIT";

export {
    UDEMY_LOAD_COURSES_SUCCESS,
    UDEMY_LOAD_COURSES_FAIL,
    UDEMY_LOAD_COURSES_INIT
}