const YOUTUBE_LOAD_LATEST_VIDEO_SUCCESS ="YOUTUBE_LOAD_LATEST_VIDEO_SUCCESS";
const YOUTUBE_LOAD_LATEST_VIDEO_FAIL ="YOUTUBE_LOAD_LATEST_VIDEO_FAIL";
const YOUTUBE_LOAD_LATEST_VIDEO_LOAD ="YOUTUBE_LOAD_LATEST_VIDEO_LOAD";

export {
    YOUTUBE_LOAD_LATEST_VIDEO_LOAD,
    YOUTUBE_LOAD_LATEST_VIDEO_SUCCESS,
    YOUTUBE_LOAD_LATEST_VIDEO_FAIL
}